ERROR - 2022-11-05 14:49:11 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-11-05 14:49:11 --> Undefined variable $productos
in APPPATH\Views\Detalle_Facturas.php on line 61.
 1 APPPATH\Views\Detalle_Facturas.php(61): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $productos', 'APPPATH\\Views\\Detalle_Facturas.php', 61)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Detalle_Facturas.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Detalle_Facturas', [], true)
 5 APPPATH\Controllers\Detalle_Facturas.php(49): view('Detalle_Facturas', [...])
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-05 22:14:09 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-11-05 22:14:09 --> Undefined variable $productos
in APPPATH\Views\Detalle_Facturas.php on line 61.
 1 APPPATH\Views\Detalle_Facturas.php(61): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $productos', 'APPPATH\\Views\\Detalle_Facturas.php', 61)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Detalle_Facturas.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Detalle_Facturas', [], true)
 5 APPPATH\Controllers\Detalle_Facturas.php(49): view('Detalle_Facturas', [...])
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-05 22:16:09 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(48): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-11-05 22:16:09 --> Undefined variable $sucursales
in APPPATH\Views\Detalle_Facturas.php on line 75.
 1 APPPATH\Views\Detalle_Facturas.php(75): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $sucursales', 'APPPATH\\Views\\Detalle_Facturas.php', 75)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Detalle_Facturas.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Detalle_Facturas', [], true)
 5 APPPATH\Controllers\Detalle_Facturas.php(51): view('Detalle_Facturas', [...])
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-05 22:16:50 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(49): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 22:18:50 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(50): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 22:20:54 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 22:21:03 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 22:21:39 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 22:21:58 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 22:26:53 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 22:45:09 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-11-05 22:45:13 --> Undefined variable $productos
in APPPATH\Views\Detalle_Facturas.php on line 61.
 1 APPPATH\Views\Detalle_Facturas.php(61): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $productos', 'APPPATH\\Views\\Detalle_Facturas.php', 61)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Detalle_Facturas.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Detalle_Facturas', [], true)
 5 APPPATH\Controllers\Detalle_Facturas.php(67): view('Detalle_Facturas', [...])
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->eliminar_detalle('1')
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-05 22:47:09 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:01:42 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:01:54 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:06:03 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:08:07 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:08:12 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:10:36 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:12:41 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:19:05 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-11-05 23:19:05 --> syntax error, unexpected variable "$sup"
in APPPATH\Views\Detalle_Facturas.php on line 130.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Detalle_Facturas', [], true)
 3 APPPATH\Controllers\Detalle_Facturas.php(53): view('Detalle_Facturas', [...])
 4 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-05 23:19:19 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-11-05 23:19:19 --> require(../Controllers/Detalle_Facturas.php): Failed to open stream: No such file or directory
in APPPATH\Views\Detalle_Facturas.php on line 129.
 1 APPPATH\Views\Detalle_Facturas.php(129): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(../Controllers/Detalle_Facturas.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\Detalle_Facturas.php', 129)
 2 APPPATH\Views\Detalle_Facturas.php(129): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Detalle_Facturas.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Detalle_Facturas', [], true)
 6 APPPATH\Controllers\Detalle_Facturas.php(53): view('Detalle_Facturas', [...])
 7 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-05 23:19:48 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-11-05 23:19:48 --> require(../Controllers/Detalle_Factura.php): Failed to open stream: No such file or directory
in APPPATH\Views\Detalle_Facturas.php on line 129.
 1 APPPATH\Views\Detalle_Facturas.php(129): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(../Controllers/Detalle_Factura.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\Detalle_Facturas.php', 129)
 2 APPPATH\Views\Detalle_Facturas.php(129): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Detalle_Facturas.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Detalle_Facturas', [], true)
 6 APPPATH\Controllers\Detalle_Facturas.php(53): view('Detalle_Facturas', [...])
 7 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-05 23:21:12 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-11-05 23:21:12 --> require(../Controllers/Detalle_Factura.php): Failed to open stream: No such file or directory
in APPPATH\Views\Detalle_Facturas.php on line 129.
 1 APPPATH\Views\Detalle_Facturas.php(129): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(../Controllers/Detalle_Factura.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\Detalle_Facturas.php', 129)
 2 APPPATH\Views\Detalle_Facturas.php(129): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Detalle_Facturas.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Detalle_Facturas', [], true)
 6 APPPATH\Controllers\Detalle_Facturas.php(53): view('Detalle_Facturas', [...])
 7 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-05 23:21:17 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:24:01 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-11-05 23:24:01 --> syntax error, unexpected variable "$sup"
in APPPATH\Views\Detalle_Facturas.php on line 131.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Detalle_Facturas', [], true)
 3 APPPATH\Controllers\Detalle_Facturas.php(53): view('Detalle_Facturas', [...])
 4 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-05 23:24:12 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-11-05 23:24:12 --> require(../Controllers/Detalle_Facturas.php): Failed to open stream: No such file or directory
in APPPATH\Views\Detalle_Facturas.php on line 130.
 1 APPPATH\Views\Detalle_Facturas.php(130): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(../Controllers/Detalle_Facturas.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\Detalle_Facturas.php', 130)
 2 APPPATH\Views\Detalle_Facturas.php(130): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Detalle_Facturas.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('Detalle_Facturas', [], true)
 6 APPPATH\Controllers\Detalle_Facturas.php(53): view('Detalle_Facturas', [...])
 7 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-05 23:25:47 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:37:14 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:38:36 --> mysqli_sql_exception: Duplicate entry '1' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:41:42 --> mysqli_sql_exception: Column 'id_sucursal' cannot be null in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:41:45 --> mysqli_sql_exception: Column 'id_sucursal' cannot be null in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:43:43 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:45:34 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:47:18 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:47:26 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:47:32 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_amatista`.`detalle_facturas`, CONSTRAINT `detalle_facturas_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `bodegas` (`id_producto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:50:09 --> mysqli_sql_exception: Duplicate entry '1' for key 'no_venta' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:50:16 --> mysqli_sql_exception: Duplicate entry '1' for key 'no_venta' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:50:46 --> mysqli_sql_exception: Duplicate entry '1' for key 'no_venta' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:50:56 --> mysqli_sql_exception: Duplicate entry '1' for key 'no_venta' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:51:24 --> mysqli_sql_exception: Duplicate entry '1' for key 'no_venta' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:56:35 --> mysqli_sql_exception: Duplicate entry '1-2' for key 'id_producto' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-11-05 23:58:04 --> mysqli_sql_exception: Duplicate entry '3' for key 'PRIMARY' in C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\app\Controllers\Detalle_Facturas.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(898): App\Controllers\Detalle_Facturas->agregar_detalle()
#9 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Detalle_Facturas))
#10 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-CodeIgniter4-proyecto-grupal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
